/* NetWizard Rack UI and editor */
(function(root){
'use strict';
const MODEL=root.NetWizardRackModel||(typeof require==='function'?require('./netwizard-rack-model.js'):null);
const arr=v=>Array.isArray(v)?v:[];
const clean=v=>String(v==null?'':v).trim();
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const clone=v=>JSON.parse(JSON.stringify(v||{}));
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
function ensureArrays(project){for(const key of ['racks','rackItems','pdus','powerConnections'])if(!Array.isArray(project[key]))project[key]=[];return project;}
function addRack(project,input){const next=ensureArrays(clone(project));const rack={id:clean(input.id)||uid('rack'),name:clean(input.name)||'Rack sin nombre',locationId:clean(input.locationId)||null,rackUnits:Math.max(1,Math.floor(num(input.rackUnits)||42)),widthMm:num(input.widthMm),depthMm:num(input.depthMm),maxLoadKg:num(input.maxLoadKg),powerCapacityWatts:num(input.powerCapacityWatts),coolingCapacityWatts:num(input.coolingCapacityWatts),numberingDirection:input.numberingDirection==='top-down'?'top-down':'bottom-up'};next.racks.push(rack);return next;}
function upsertRackItem(project,input){const next=ensureArrays(clone(project));const type=clean(input.type)||'other';const item={id:clean(input.id)||uid('rackitem'),rackId:clean(input.rackId),type,label:clean(input.label)||clean(input.name)||type,startUnit:num(input.startUnit),heightUnits:Math.max(1,Math.floor(num(input.heightUnits)||1)),face:clean(input.face)||'front',mounting:clean(input.mounting)||null,weightKg:num(input.weightKg),powerDrawWatts:num(input.powerDrawWatts)};if(type==='device'&&clean(input.deviceId))item.deviceId=clean(input.deviceId);const index=next.rackItems.findIndex(x=>x.id===item.id);if(index>=0)next.rackItems[index]=Object.assign({},next.rackItems[index],item);else next.rackItems.push(item);if(item.deviceId){const d=arr(next.devices).find(x=>x.id===item.deviceId);if(d){d.rackId=item.rackId;d.rackUnit=item.startUnit;d.rackUnits=item.heightUnits;d.rackFace=item.face;}}
return next;}
function addPdu(project,input){const next=ensureArrays(clone(project));next.pdus.push({id:clean(input.id)||uid('pdu'),rackId:clean(input.rackId),name:clean(input.name)||'PDU',feed:clean(input.feed)||'A',mounting:clean(input.mounting)||'vertical-rear',voltage:num(input.voltage)||230,maxCurrentAmps:num(input.maxCurrentAmps),maxPowerWatts:num(input.maxPowerWatts),outletCount:Math.max(1,Math.floor(num(input.outletCount)||8))});return next;}
function addPowerConnection(project,input){const next=ensureArrays(clone(project));next.powerConnections.push({id:clean(input.id)||uid('power'),deviceId:clean(input.deviceId),powerSupplyIndex:Math.max(0,Math.floor(num(input.powerSupplyIndex)||0)),pduId:clean(input.pduId),outlet:Math.max(1,Math.floor(num(input.outlet)||1)),feed:clean(input.feed)||null});return next;}
function removeEntity(project,kind,id){const next=ensureArrays(clone(project));const map={rack:'racks',rackItem:'rackItems',pdu:'pdus',powerConnection:'powerConnections'};const key=map[kind];if(!key)return next;if(kind==='rack'){const removedPduIds=new Set(next.pdus.filter(x=>x.rackId===id).map(x=>x.id));next.racks=next.racks.filter(x=>x.id!==id);next.rackItems=next.rackItems.filter(x=>x.rackId!==id);next.pdus=next.pdus.filter(x=>x.rackId!==id);next.powerConnections=next.powerConnections.filter(x=>!removedPduIds.has(x.pduId));for(const d of arr(next.devices))if((d.rackId||d.rack)===id){d.rackId=null;d.rack=null;d.rackUnit=null;d.rackUnits=null;d.rackFace=null;}return next;}next[key]=next[key].filter(x=>x.id!==id);if(kind==='pdu')next.powerConnections=next.powerConnections.filter(x=>x.pduId!==id);if(kind==='rackItem'){for(const d of arr(next.devices))if(d.id===arr(project.rackItems).find(x=>x.id===id)?.deviceId){d.rackId=null;d.rack=null;d.rackUnit=null;d.rackUnits=null;d.rackFace=null;}}return next;}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text??'');return n;}
function field(label,node){const w=el('div','');w.append(el('label','fl',label),node);return w;}
function input(type,placeholder,value){const n=document.createElement('input');n.type=type||'text';if(placeholder)n.placeholder=placeholder;if(value!=null)n.value=value;return n;}
function select(options,value){const n=document.createElement('select');for(const [v,l] of options){const o=document.createElement('option');o.value=v;o.textContent=l;o.selected=String(v)===String(value??'');n.appendChild(o);}return n;}
function button(text,cls,action){const b=el('button',`btn ${cls||'bs'}`,text);b.type='button';if(action)b.dataset.action=action;return b;}
function ensureLayoutCss(){if(!root.document||root.document.querySelector('link[data-netwizard-layout]'))return;const link=root.document.createElement('link');link.rel='stylesheet';link.href='./css/netwizard-layout.css';link.dataset.netwizardLayout='1';root.document.head.appendChild(link);}
function rackDiagram(project,rack){const box=el('div','rack-diagram');const items=MODEL.allRackItems(project).filter(x=>x.rackId===rack.id);for(let u=rack.rackUnits;u>=1;u--){const row=el('div','rack-u');const label=el('div','rack-u-label',`U${u}`);const hit=items.find(i=>u>=Number(i.startUnit)&&u<Number(i.startUnit)+Number(i.heightUnits||1));const content=el('div',hit?'rack-u-used':'rack-u-free',hit?(hit.label||hit.name||hit.type):'Libre');row.append(label,content);box.appendChild(row);}return box;}
function editorCard(project){const card=el('div','card nw-card-wide');card.appendChild(el('div','card-t','✏️ Editor de racks y alimentación'));const tabs=el('div','rack-editor-grid');
const rackForm=el('form','rack-editor-form');rackForm.dataset.form='rack';const rackName=input('text','Rack principal');const rackUnits=input('number','42',42);rackUnits.min='1';const rackLocation=select([['','Sin ubicación'],...arr(project.physicalLocations).map(x=>[x.id,x.name||x.id])],'');const rackPower=input('number','7000');rackForm.append(field('Nombre',rackName),field('Unidades',rackUnits),field('Ubicación',rackLocation),field('Capacidad eléctrica W',rackPower),button('➕ Crear rack','bp','add-rack'));rackForm.elementsRef={rackName,rackUnits,rackLocation,rackPower};
const itemForm=el('form','rack-editor-form');itemForm.dataset.form='item';const itemRack=select(arr(project.racks).map(x=>[x.id,x.name||x.id]),'');const itemType=select([['device','Equipo'],['patch-panel','Patch panel'],['cable-manager','Pasacables'],['shelf','Bandeja'],['ups','UPS'],['blanking-panel','Panel ciego'],['other','Otro']],'device');const itemDevice=select([['','Sin equipo'],...arr(project.devices).map(x=>[x.id,x.name||x.id])],'');const itemLabel=input('text','Patch panel Cat6A');const itemStart=input('number','20');itemStart.min='1';const itemHeight=input('number','1',1);itemHeight.min='1';itemForm.append(field('Rack',itemRack),field('Tipo',itemType),field('Equipo',itemDevice),field('Etiqueta',itemLabel),field('Unidad inicial',itemStart),field('Altura U',itemHeight),button('➕ Colocar elemento','bp','add-item'));itemForm.elementsRef={itemRack,itemType,itemDevice,itemLabel,itemStart,itemHeight};
const pduForm=el('form','rack-editor-form');pduForm.dataset.form='pdu';const pduRack=select(arr(project.racks).map(x=>[x.id,x.name||x.id]),'');const pduName=input('text','PDU-A');const pduFeed=select([['A','Alimentación A'],['B','Alimentación B'],['UPS','UPS']],'A');const pduOutlets=input('number','12',12);pduOutlets.min='1';const pduPower=input('number','3680');pduForm.append(field('Rack',pduRack),field('Nombre',pduName),field('Feed',pduFeed),field('Tomas',pduOutlets),field('Potencia máxima W',pduPower),button('➕ Crear PDU','bp','add-pdu'));pduForm.elementsRef={pduRack,pduName,pduFeed,pduOutlets,pduPower};
const powerForm=el('form','rack-editor-form');powerForm.dataset.form='power';const powerDevice=select(arr(project.devices).map(x=>[x.id,x.name||x.id]),'');const powerPdu=select(arr(project.pdus).map(x=>[x.id,x.name||x.id]),'');const powerOutlet=input('number','1',1);powerOutlet.min='1';const powerPsu=input('number','0',0);powerPsu.min='0';powerForm.append(field('Equipo',powerDevice),field('PDU',powerPdu),field('Toma',powerOutlet),field('Fuente nº',powerPsu),button('🔌 Conectar alimentación','bp','add-power'));powerForm.elementsRef={powerDevice,powerPdu,powerOutlet,powerPsu};
for(const [title,form] of [['Nuevo rack',rackForm],['Elemento de rack',itemForm],['PDU / regleta',pduForm],['Conexión eléctrica',powerForm]]){const group=el('section','rack-editor-group');group.append(el('h3','',title),form);tabs.appendChild(group);}card.appendChild(tabs);return card;}
function summaryCard(project,rack,validation){const card=el('div','card');const h=el('div','card-h');h.append(el('div','card-t',`🗄 ${rack.name||rack.id}`),el('span','b bac',`${rack.rackUnits}U`));const del=button('Eliminar','bd bxs','remove-rack');del.dataset.id=rack.id;h.appendChild(del);card.appendChild(h);const loc=arr(project.physicalLocations).find(x=>x.id===rack.locationId);card.appendChild(el('div','hint',`${loc?loc.name:'Ubicación no definida'} · ${rack.widthMm||'—'}×${rack.depthMm||'—'} mm`));const grid=el('div','g2 nw-grid-adaptive');grid.appendChild(rackDiagram(project,rack));const details=el('div','nw-panel-stack');const issues=arr(validation.issues).filter(i=>i.rackId===rack.id);const items=MODEL.allRackItems(project).filter(i=>i.rackId===rack.id);const used=new Set();items.forEach(i=>{for(let u=Number(i.startUnit);u<Number(i.startUnit)+Number(i.heightUnits||1);u++)used.add(u);});details.append(el('p','',`Ocupación: ${used.size}/${rack.rackUnits}U`),el('p','',`Elementos: ${items.length}`),el('p','',`Incidencias: ${issues.length}`));const pdus=arr(project.pdus).filter(x=>x.rackId===rack.id);details.appendChild(el('p','',`PDU/regletas: ${pdus.length}`));for(const pdu of pdus){const line=el('div','rack-list-row');line.append(el('span','',`${pdu.name||pdu.id} · ${pdu.outletCount||0} tomas · feed ${pdu.feed||'—'}`));const b=button('Quitar','bd bxs','remove-pdu');b.dataset.id=pdu.id;line.appendChild(b);details.appendChild(line);}if(issues.length){const ul=el('ul','rack-issues');issues.slice(0,8).forEach(i=>ul.appendChild(el('li','',i.message)));details.appendChild(ul);}grid.append(details);card.appendChild(grid);return card;}
function connectionsCard(project){const card=el('div','card nw-card-wide');card.appendChild(el('div','card-t','🔌 Conexiones de alimentación'));const list=el('div','nw-panel-stack');for(const c of arr(project.powerConnections)){const d=arr(project.devices).find(x=>x.id===c.deviceId),p=arr(project.pdus).find(x=>x.id===c.pduId);const row=el('div','rack-list-row');row.appendChild(el('span','',`${d?.name||c.deviceId||'Equipo'} PSU-${Number(c.powerSupplyIndex||0)+1} → ${p?.name||c.pduId||'PDU'} / toma ${c.outlet||'—'}`));const b=button('Quitar','bd bxs','remove-power');b.dataset.id=c.id;row.appendChild(b);list.appendChild(row);}if(!arr(project.powerConnections).length)list.appendChild(el('div','empty','No hay conexiones eléctricas definidas.'));card.appendChild(list);return card;}
function render(project){ensureLayoutCss();project=ensureArrays(clone(project));const wrap=el('div','nw-panel-stack');const validation=MODEL.validate(project);const head=el('div','card nw-card-wide');const hh=el('div','card-h');hh.append(el('div','card-t','🗄 Racks, alimentación y material pasivo'),el('span',`b ${validation.ok?'bgn':'brd'}`,validation.ok?'Sin bloqueos':`${validation.issues.length} incidencias`));head.appendChild(hh);head.appendChild(el('p','hint','Crea racks, coloca equipos y material pasivo por unidades, define PDU y conecta fuentes de alimentación.'));wrap.append(head,editorCard(project));if(validation.racks.length){const rackGrid=el('div','nw-card-grid');validation.racks.forEach(r=>rackGrid.appendChild(summaryCard(project,r,validation)));wrap.appendChild(rackGrid);}else wrap.appendChild(el('div','co co-yw','No hay racks definidos. Usa el editor para crear el primero.'));wrap.appendChild(connectionsCard(project));const bom=MODEL.billOfMaterials(project);const card=el('div','card nw-card-wide');card.appendChild(el('div','card-t','📦 Materiales de rack'));const ul=el('ul','');bom.forEach(x=>ul.appendChild(el('li','',`${x.quantity} × ${x.description||x.label||x.name||x.kind||x.type||'Material'}`)));if(!bom.length)ul.appendChild(el('li','empty','No hay materiales definidos.'));card.appendChild(ul);wrap.appendChild(card);return wrap;}
function bind(mount,state){mount.onclick=e=>{const action=e.target&&e.target.dataset&&e.target.dataset.action;if(!action)return;const snapshot=state.getSnapshot();let next=snapshot;if(action==='add-rack'){const f=mount.querySelector('[data-form="rack"]');const r=f.elementsRef;next=addRack(snapshot,{name:r.rackName.value,rackUnits:r.rackUnits.value,locationId:r.rackLocation.value,powerCapacityWatts:r.rackPower.value});}
if(action==='add-item'){const f=mount.querySelector('[data-form="item"]');const r=f.elementsRef;next=upsertRackItem(snapshot,{rackId:r.itemRack.value,type:r.itemType.value,deviceId:r.itemDevice.value,label:r.itemLabel.value,startUnit:r.itemStart.value,heightUnits:r.itemHeight.value});}
if(action==='add-pdu'){const f=mount.querySelector('[data-form="pdu"]');const r=f.elementsRef;next=addPdu(snapshot,{rackId:r.pduRack.value,name:r.pduName.value,feed:r.pduFeed.value,outletCount:r.pduOutlets.value,maxPowerWatts:r.pduPower.value});}
if(action==='add-power'){const f=mount.querySelector('[data-form="power"]');const r=f.elementsRef;const pdu=arr(snapshot.pdus).find(x=>x.id===r.powerPdu.value);next=addPowerConnection(snapshot,{deviceId:r.powerDevice.value,pduId:r.powerPdu.value,outlet:r.powerOutlet.value,powerSupplyIndex:r.powerPsu.value,feed:pdu&&pdu.feed});}
if(action==='remove-rack')next=removeEntity(snapshot,'rack',e.target.dataset.id);if(action==='remove-pdu')next=removeEntity(snapshot,'pdu',e.target.dataset.id);if(action==='remove-power')next=removeEntity(snapshot,'powerConnection',e.target.dataset.id);if(next!==snapshot)state.replaceProject(next,{source:'rack-editor'});};}
function inject(){if(!root.document||!MODEL)return;ensureLayoutCss();const page=root.document.getElementById('pg-physical')||root.document.getElementById('pg-dev')||root.document.getElementById('pg-dash');const state=root.NetWizardState;if(!page||!state||typeof state.getSnapshot!=='function')return;let mount=root.document.getElementById('rackPlannerMount');if(!mount){mount=root.document.createElement('div');mount.id='rackPlannerMount';mount.dataset.layoutSection='full';page.appendChild(mount);}mount.textContent='';mount.appendChild(render(state.getSnapshot()));bind(mount,state);}
const api={version:'netwizard-rack-ui-v3.1',render,inject,ensureLayoutCss,ensureArrays,addRack,upsertRackItem,addPdu,addPowerConnection,removeEntity};root.NetWizardRackUi=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root.document){root.document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,0));root.document.addEventListener('nw:project:changed',()=>setTimeout(inject,0));}
})(typeof window!=='undefined'?window:globalThis);