/* NetWizard Rack UI */
(function(root){
'use strict';
const MODEL=root.NetWizardRackModel||(typeof require==='function'?require('./netwizard-rack-model.js'):null);
const arr=v=>Array.isArray(v)?v:[];
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text??'');return n;}
function ensureLayoutCss(){if(!root.document||root.document.querySelector('link[data-netwizard-layout]'))return;const link=root.document.createElement('link');link.rel='stylesheet';link.href='./css/netwizard-layout.css';link.dataset.netwizardLayout='1';root.document.head.appendChild(link);}
function rackDiagram(project,rack){const box=el('div','rack-diagram');box.style.cssText='border:1px solid var(--b1);border-radius:10px;overflow:hidden;background:var(--s2)';const items=MODEL.allRackItems(project).filter(x=>x.rackId===rack.id);for(let u=rack.rackUnits;u>=1;u--){const row=el('div','rack-u');row.style.cssText='display:grid;grid-template-columns:52px minmax(0,1fr);border-bottom:1px solid var(--b1);min-height:24px';const label=el('div','',`U${u}`);label.style.cssText='padding:4px 7px;background:var(--s3);font-size:11px;font-weight:700';const hit=items.find(i=>u>=i.startUnit&&u<i.startUnit+i.heightUnits);const content=el('div','',hit?(hit.label||hit.name||hit.type):'Libre');content.style.cssText=`padding:4px 8px;font-size:11px;${hit?'background:var(--acd);font-weight:700':'color:var(--t4)'}`;row.append(label,content);box.appendChild(row);}return box;}
function summaryCard(project,rack,validation){const card=el('div','card');const h=el('div','card-h');h.append(el('div','card-t',`🗄 ${rack.name||rack.id}`),el('span','b bac',`${rack.rackUnits}U`));card.appendChild(h);const loc=arr(project.physicalLocations).find(x=>x.id===rack.locationId);card.appendChild(el('div','hint',`${loc?loc.name:'Ubicación no definida'} · ${rack.widthMm||'—'}×${rack.depthMm||'—'} mm`));const grid=el('div','g2 nw-grid-adaptive');grid.style.marginTop='10px';grid.appendChild(rackDiagram(project,rack));const details=el('div','nw-panel-stack');const issues=arr(validation.issues).filter(i=>i.rackId===rack.id);const items=MODEL.allRackItems(project).filter(i=>i.rackId===rack.id);const used=new Set();items.forEach(i=>{for(let u=i.startUnit;u<i.startUnit+i.heightUnits;u++)used.add(u);});details.append(el('p','',`Ocupación: ${used.size}/${rack.rackUnits}U`),el('p','',`Elementos: ${items.length}`),el('p','',`Incidencias: ${issues.length}`));const pdus=arr(project.pdus).filter(x=>x.rackId===rack.id);details.appendChild(el('p','',`PDU/regletas: ${pdus.length}`));if(issues.length){const ul=el('ul','');issues.slice(0,8).forEach(i=>ul.appendChild(el('li','',i.message)));details.appendChild(ul);}grid.append(details);card.appendChild(grid);return card;}
function render(project){ensureLayoutCss();const wrap=el('div','nw-panel-stack');const validation=MODEL.validate(project||{});const head=el('div','card nw-card-wide');const hh=el('div','card-h');hh.append(el('div','card-t','🗄 Racks, alimentación y material pasivo'),el('span',`b ${validation.ok?'bgn':'brd'}`,validation.ok?'Sin bloqueos':`${validation.issues.length} incidencias`));head.appendChild(hh);head.appendChild(el('p','hint','Vista esquemática de ocupación, PDU, patch panels, pasacables y equipos instalados.'));wrap.appendChild(head);if(!validation.racks.length){wrap.appendChild(el('div','co co-yw','No hay racks definidos. Añade project.racks y asigna rackId/rackUnit a los equipos.'));return wrap;}const rackGrid=el('div','nw-card-grid');validation.racks.forEach(r=>rackGrid.appendChild(summaryCard(project,r,validation)));wrap.appendChild(rackGrid);const bom=MODEL.billOfMaterials(project);const card=el('div','card nw-card-wide');card.appendChild(el('div','card-t','📦 Materiales de rack'));const ul=el('ul','');bom.forEach(x=>ul.appendChild(el('li','',`${x.quantity} × ${x.description||x.label||x.name||x.kind||x.type||'Material'}`)));card.appendChild(ul);wrap.appendChild(card);return wrap;}
function inject(){if(!root.document||!MODEL)return;ensureLayoutCss();const page=root.document.getElementById('pg-physical')||root.document.getElementById('pg-dev')||root.document.getElementById('pg-dash');const state=root.NetWizardState;if(!page||!state||typeof state.getSnapshot!=='function')return;let mount=root.document.getElementById('rackPlannerMount');if(!mount){mount=root.document.createElement('div');mount.id='rackPlannerMount';mount.dataset.layoutSection='full';page.appendChild(mount);}mount.textContent='';mount.appendChild(render(state.getSnapshot()));}
const api={version:'netwizard-rack-ui-v2',render,inject,ensureLayoutCss};root.NetWizardRackUi=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root.document){root.document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,0));root.document.addEventListener('nw:project:changed',()=>setTimeout(inject,0));}
})(typeof window!=='undefined'?window:globalThis);
