'use strict';
const assert=require('assert');
const UI=require('../js/netwizard-rack-ui.js');
let project={devices:[{id:'sw1',name:'SW-01'}],physicalLocations:[{id:'room1',name:'CPD'}]};
project=UI.addRack(project,{id:'rack1',name:'Rack principal',locationId:'room1',rackUnits:24,powerCapacityWatts:4000});
assert.strictEqual(project.racks.length,1);
assert.strictEqual(project.racks[0].rackUnits,24);
project=UI.upsertRackItem(project,{id:'item1',rackId:'rack1',type:'device',deviceId:'sw1',label:'SW-01',startUnit:20,heightUnits:1});
assert.strictEqual(project.rackItems.length,1);
assert.strictEqual(project.devices[0].rackId,'rack1');
assert.strictEqual(project.devices[0].rackUnit,20);
project=UI.addPdu(project,{id:'pdu1',rackId:'rack1',name:'PDU-A',feed:'A',outletCount:12,maxPowerWatts:3680});
assert.strictEqual(project.pdus[0].outletCount,12);
project=UI.addPowerConnection(project,{id:'power1',deviceId:'sw1',pduId:'pdu1',outlet:3,powerSupplyIndex:0,feed:'A'});
assert.strictEqual(project.powerConnections[0].outlet,3);
const untouched={devices:project.devices.length,racks:project.racks.length};
const removed=UI.removeEntity(project,'pdu','pdu1');
assert.strictEqual(removed.pdus.length,0);
assert.strictEqual(removed.powerConnections.length,0);
assert.deepStrictEqual(untouched,{devices:removed.devices.length,racks:removed.racks.length});
const cleared=UI.removeEntity(project,'rack','rack1');
assert.strictEqual(cleared.racks.length,0);
assert.strictEqual(cleared.rackItems.length,0);
assert.strictEqual(cleared.pdus.length,0);
assert.strictEqual(cleared.devices[0].rackId,null);
console.log('✓ Editor de racks crea, coloca, conecta y elimina entidades manteniendo referencias coherentes');
